server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/drivestudiodownload
spring.datasource.username=drivestudio_user
spring.datasource.password=Slavic1990!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

upload.directory=/app/uploads

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
