# Port aplica?ie
server.port=8080

# Baza de date H2 (in-memory)
spring.datasource.url=jdbc:h2:mem:drivestudio
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# JWT
jwt.secret=FEX_SECRET_KEY
jwt.expiration=3600000

# Upload folder (în container)
upload.directory=/app/uploads

# Logging
logging.level.org.springframework=INFO
spring.main.allow-bean-definition-overriding=true

