server.port=8080

spring.datasource.url=jdbc:mariadb://77.89.196.226:3306/drivestudiodownload
spring.datasource.username=drivestudio_user
spring.datasource.password=Slavic1990!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

upload.directory=F:/DriveStudioNou/uploads

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
spring.mvc.servlet.path=/
